#2023-10-15 09:30
name: act - Magisk Build - release

env:
  TAG_NAME:      "Magisk"
  TAG_VERSION:   "Magisk-v26.3.1"
  TAG_BUILD:     "-b"
  TAG_REF:       "0000000"
  PROG_NAME:     "Magisk"
  PROG_VERSION:  "v26.3.1"
  VERSION:       "26.3.1"
  #signing keys env variable checks
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'
  #  signingKeyBase64: '${{ secrets.ANDROID_SIGNING_KEY }}'
  #  alias:            '${{ secrets.ANDROID_ALIAS }}'
  #  keyStorePassword: '${{ secrets.ANDROID_KEY_STORE_PASSWORD }}'
  #  keyPassword:      '${{ secrets.ANDROID_KEY_PASSWORD }}'

on:
#  push:
#    branches: [master]
#    paths:
#      - "app/**"
#      - "native/**"
#      - "stub/**"
#      - "buildSrc/**"
#      - "build.py"
#      - "gradle.properties"
#      - ".github/workflows/build.yml"
#  pull_request:
#    branches: [master]
  workflow_dispatch:
    inputs:
      patch_ondk: 
          description: patch ondk url
          type: boolean
          default: true
          required: true
      build_debug: 
          description: build debug
          type: boolean
          default: false
          required: true
      symbols: 
          description: Upload symbols
          type: boolean
          default: false
          required: true
      run_tests: 
          description: Run tests
          type: boolean
          default: false
          required: true

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Check out
        uses: deep-soft/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: get version code
        shell: bash
        run: |
          _version_code_=$(grep "magisk.versionCode" gradle.properties | awk -F"=" '{print $2}')
          if [[ "$_version_code_" != "" ]]; then
            echo "PROG_VERSION_CODE=$_version_code_" >> $GITHUB_ENV
            _sver2_=${_version_code_:${#_version_code_}-2:2}
            _ver_sver_=${_version_code_:0:${#_version_code_}-2}
            _sver_=${_ver_sver_:${#_ver_sver_}-1:1}
            _ver_=${_ver_sver_:0:-1}
            _ver_sver_sver2_=$_ver_.$_sver_.$_sver2_

            echo "VERSION=$_ver_sver_sver2_" >> $GITHUB_ENV
            echo "PROG_VERSION=v$_ver_sver_sver2_" >> $GITHUB_ENV
          fi

      - name: print version, program version
        shell: bash
        run: |
            echo "VERSION=${{ env.VERSION }}"
            echo "PROG_VERSION=${{ env.PROG_VERSION }}"

      - name: patch ondk url in build.py
        if: ${{ inputs.patch_ondk }}
        shell: bash
        run: |
          grep "/ondk/" build.py
          sed -ibak "s!github.com\/topjohnwu\/ondk\/releases\/!github.com\/deep-soft\/ondk\/releases\/!" build.py
          grep "/ondk/" build.py

      - name: Set up JDK 17
        uses: deep-soft/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Python 3
        uses: deep-soft/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up sccache
        uses: deep-soft/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}
          max-size: 10000M

      - name: Cache Gradle dependencies
        uses: deep-soft/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: deep-soft/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: Set up NDK
        run: python build.py -v ndk

      - name: Build release
        run: |
          python build.py -vr all

      - name: Copy apk to signed-apk
        shell: bash
        run: |
          mkdir -p signed-apk;
          cp ./out/app-release.apk ./signed-apk/${{ env.PROG_NAME }}-${{ env.PROG_VERSION }}.apk
#          if [[ "${{ env.PROG_VERSION_CODE }}" == "" ]]; then
#            cp ./out/app-release.apk ./signed-apk/${{ env.PROG_NAME }}-${{ env.PROG_VERSION }}.apk
#          else
#            cp ./out/app-release.apk ./signed-apk/${{ env.PROG_NAME }}-v${{ env.PROG_VERSION_CODE }}.apk
#          fi;

      - uses: deep-soft/sign-android-release@master
        name: Sign app APK
        if: env.ANDROID_SIGNING_KEY != null
        id: sign-magisk
        with:
          releaseDirectory: ./signed-apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Publish Release
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ./out/*.apk
            ${{steps.sign-magisk.outputs.signedReleaseFile}}

      - name: Build debug
        if: ${{ inputs.build_debug }}
        run: |
          python build.py -v all

      - name: Stop gradle daemon
        run: ./gradlew --stop

      # Only upload artifacts built on Linux
      - name: Upload build artifact
        if: runner.os == 'Linux'
        uses: deep-soft/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: out

      - name: Upload mapping and native debug symbols
        if: (${{ inputs.run_tests }} && runner.os == 'Linux')
        uses: deep-soft/upload-artifact@v3
        with:
          name: ${{ github.sha }}-symbols
          path: app/build/outputs

  test:
    name: Test on ${{ matrix.api }}
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        api: [23, 26, 28, 29, 34]

    steps:
      - name: Check out
        uses: deep-soft/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: deep-soft/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Python 3
        uses: deep-soft/setup-python@v4
        with:
          python-version: "3.x"

      - name: Download build artifacts
        uses: deep-soft/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: out

      - name: AVD test
        run: |
          # brew install coreutils bash
          scripts/avd_test.sh ${{ matrix.api }}
